# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FOIA.gov - Freedom of Information Act
description: > # this means to ignore newlines until "baseurl:"
  The Freedom of Information Act (FOIA) is a law that gives you the right to
  access information from the federal government. It is often described as the
  law that keeps citizens in the know about their government.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
timezone: America/New_York

navigation:
  primary:
    - href: /
      title: Home
    - href: /request/
      title: Request
    - href: /data.html
      title: Data
    - href: /reports.html
      title: Reports
    - href: /search.html
      title: Find
    - href: /about.html
      title: Learn
  secondary:
    - href: /news.html
      title: News
    - href: /glossary.html
      title: Glossary
    - href: /faq.html
      title: FAQs
    - href: /index-es.html
      title: en Espa&ntilde;ol
    - href: /feedback.html
      title: Feedback
    - href: /report-makerequest.html
      title: FOIA Contacts

collections:
  api:
    output: true

defaults:
  - scope:
      path: ''
      type: api
    values:
      layout: json
      permalink: /:collection/:path.json

# Build settings
markdown: kramdown
source: www.foia.gov
include:
  - .bp-config
  - .htaccess
  - .htpasswd
exclude:
  - README.md
