version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - type: cache-restore
        key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - type: cache-save
        key: v1-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - type: cache-restore
        key: v1-node-modules-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - type: cache-save
        key: v1-node-modules-{{ checksum "package.json" }}
        paths:
          - node_modules
      - run:
          name: Prod build
          command: NODE_ENV=production make build
      - persist_to_workspace:
          root: .
          paths:
            - _site
      - run:
          name: Run tests
          command: make test

  deploy:
    docker:
      - image: 18fgsa/cloud-foundry-cli
        environment:
          CF_API: https://api.fr.cloud.gov

    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Generate htpasswd
          command: bin/gen_htpasswd.sh _site/.htpasswd
      - deploy:
          name: cf push
          command: cf_deploy.sh foia-dot-gov doj-foia-discovery staging


workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
